[toolchain]
channel = "1.76.0"
components = [ "rustfmt", "rustc-dev", "clippy", "cargo", "rust-std" ]
targets = [
    "x86_64-unknown-linux-musl",
    "i686-unknown-linux-musl",
    "aarch64-unknown-linux-musl",
    "x86_64-pc-windows-gnu"
]
